# Generated by Django 4.0.6 on 2022-08-28 15:23

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('role_sought', models.CharField(choices=[('C Suite', 'C Suite'), ('Data Engineerg', 'Data Engineerg'), ('Data Science', 'Data Science'), ('Engineering', 'Engineering'), ('Front End Engineer', 'Front End Engineer'), ('Product Management', 'Product Management'), ('Sales Entry', 'Sales Entry'), ('Sales Exec', 'Sales Exec'), ('Sales Mid-level', 'Sales Mid-level'), ('UX Designer', 'UX Designer'), ('Other', 'Other')], max_length=80)),
                ('role_sought_other', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('New York', 'New York'), ('London', 'London'), ('Los Angeles', 'Los Angeles'), ('San Francisco', 'San Francisco'), ('Seattle', 'Seattle'), ('Chicago', 'Chicago'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=50)),
                ('location_other', models.CharField(blank=True, max_length=100, null=True)),
                ('funding_stage', models.CharField(choices=[('Seed Round', 'Seed Round'), ('Post Seed', 'Post Seed'), ('A Round', 'A Round'), ('B Round', 'B Round'), ('C Round ', 'C Round '), ('Late Stage (post C)', 'Late Stage (post C)'), ('Public', 'Public')], max_length=50)),
                ('funding_amount', models.CharField(choices=[('<$1M', '<$1M'), ('$1m - $2m', '$1m - $2m'), ('$2m - $5m', '$2m - $5m'), ('$5m - $10m', '$5m - $10m'), ('$10m - $20m', '$10m - $20m'), ('$20m - $50m', '$20m - $50m'), ('$50m+', '$50m+')], max_length=12)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Product', 'Product'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Other', 'Other')], max_length=50)),
                ('salary_range', models.CharField(choices=[('$50k - $75k', '$50k - $75k'), ('$75k - $100k', '$75k - $100k'), ('$100k - $125k', '$100k - $125k'), ('$125k - $175k', '$125k - $175k'), ('$175k - $200k', '$175k - $200k'), ('$200k+', '$200k+'), ('Commision-based', 'Commision-based')], max_length=50, null=True)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=30, null=True)),
                ('remote', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('field_exp', models.IntegerField(default=0)),
                ('proptech_exp', models.IntegerField(default=0)),
                ('desired_salary', models.IntegerField(blank=True, null=True)),
                ('cloud', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AWS', 'AWS'), ('GCP', 'GCP'), ('Azure', 'Azure')], max_length=13, null=True)),
                ('languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Java', 'Java'), ('C++', 'C++'), ('Python', 'Python')], max_length=15, null=True)),
                ('property_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Multifamily', 'Multifamily'), ('Retail', 'Retail'), ('Office', 'Office'), ('Industrial', 'Industrial'), ('Hotel', 'Hotel'), ('Other', 'Other')], max_length=48, null=True)),
                ('skills_req', models.CharField(max_length=200)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_applicant', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_job', to='Company.job')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='Company.job')),
            ],
        ),
    ]
