# Generated by Django 4.0.6 on 2022-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('New York', 'New York'), ('London', 'London'), ('Los Angeles', 'Los Angeles'), ('San Francisco', 'San Francisco'), ('Seattle', 'Seattle'), ('Chicago', 'Chicago'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('Yes', True), ('No', False)], max_length=20),
        ),
    ]
